FROM ubuntu:20.04

COPY a/requirements.txt /app/requirements.txt
COPY a/app.py /app/app.py


WORKDIR /app

RUN apt update -y && apt install -y python3 python3-pip python3-dev
RUN pip3 install -r requirements.txt

EXPOSE 80

CMD [ "python3","app.py" ]